name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install required packages
      run: |
        sudo install shellcheck
        pip install --upgrade pip
        pip install vim-vint
    # Lint check
    - name: Check bin/install.sh
      if: always()
      run: shellcheck ${GITHUB_WORKSPACE}/bin/install.sh

    - name: Check nvim/init.vim
      if: always()
      run: vint ${GITHUB_WORKSPACE}/nvim/*.vim -cstV --enable-neovim
